language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g github-label-sync
install:
  - travis_retry npm install
stages:
  - test
  - name: deploy
    if: repo = seantrane/github-label-presets
        AND type != pull_request
        AND branch = master
jobs:
  include:
    - stage: test
      name: 'Checks and Tests'
      script:
        - commitlint-travis
        - npm run lint
        - travis_retry github-label-sync -a "$GH_TOKEN" -d -l ${PWD}/labels.json
    - stage: deploy
      name: 'Publish and Release'
      script:
        - travis_retry github-label-sync -a "$GH_TOKEN" -l ${PWD}/labels.json
        - npm run semantic-release
