---
name: Continuous Integration

on:
  pull_request:
    branches: [master, main, 'releases/**', 'feat/**', 'fix/**']
  push:
    branches: [main]
    paths:
      - '.github/workflows/integration.yml'
      - '.github/workflows/linter.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  linter:
    name: Super-Linter
    uses: ./.github/workflows/linter.yml

  semantic_pr:
    name: Semantic Pull Request
    if: ${{ github.base_ref != '' || github.event_name == 'pull_request' }}
    uses: ./.github/workflows/semantic-pr.yml
