---
name: Continuous Integration

on:
  pull_request_target:
    branches: [master, main, 'releases/**']

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Load Super-Linter Config
        run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
