---
name: Continuous Integration

on:
  pull_request_target:
    branches: [master, main, 'releases/**', 'feat/**', 'fix/**']

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/linter.yml
